### ISSUE TITLE
Plugin causing nvim to (silently) exit with status 134

### ISSUE THREAD

**Issue by prurph** [antosha417/nvim-lsp-file-operations#24]
I'm using nvim 0.9.4 on macOS 14.1.1 and I've noticed enabling this plugin causes nvim to exit with an error status:

```sh
$ nvim
$ echo $?
134
```

This happens consistently when the plugin is enabled, even just loading vim and immediately quitting is sufficient. There is no error message or log that I can see, but it causes issues with programs using `EDITOR` and then expecting a zero status from saving and quitting.

I enabled the debug log for `nvim-lsp-file-operations` but all it shows is:

```
[DEBUG Sat Dec  2 22:30:53 2023] /Users/me/.local/share/LazyVim/lazy/nvim-lsp-file-operations/lua/lsp-file-operations.lua:27: Setting up neo-tree integration
[DEBUG Sat Dec  2 22:30:53 2023] /Users/me/.local/share/LazyVim/lazy/nvim-lsp-file-operations/lua/lsp-file-operations.lua:56: Neo-tree integration setup complete
[DEBUG Sat Dec  2 22:32:17 2023] /Users/me/.local/share/LazyVim/lazy/nvim-lsp-file-operations/lua/lsp-file-operations.lua:27: Setting up neo-tree integration
[DEBUG Sat Dec  2 22:32:17 2023] /Users/me/.local/share/LazyVim/lazy/nvim-lsp-file-operations/lua/lsp-file-operations.lua:56: Neo-tree integration setup complete
```

Any thoughts on how to proceed debugging? Thanks![](url)

**Comment by antosha417** [comment]
Hey @prurph! Tank you for reporting your issue here. 
Personally, I don't use neo-tree. Instead, I use this plugin with nvim-tree. To start debugging and help resolve the issue, let's try to reproduce it with a minimal configuration. You can run Neovim with the minimal config using the following command:

```shell
nvim -u minimal_init.lua
```

This is an example of `minimal_init.lua` for `nvim-tree`
```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"

local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      "nvim-lua/plenary.nvim",
      "antosha417/nvim-lsp-file-operations",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end

if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end

load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true

-- MODIFY THIS SETUP FUNCTION TO SET UP PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
  require("lsp-file-operations").setup {
    debug = true,
  }
end
```

**Comment by prurph** [comment]
Hi, thank you for responding! I dug in and found I was able to reproduce the issue without nvim-lsp-file-operations. It seems to be with the 3rd/image.nvim plugin, however very strangely in my "full" LazyVim setup, I don't get the issue with image.nvim enabled when I disable nvim-lsp-file-operations, but I can repro the issue without nvim-lsp-file-operations entirely (!?) so there must be something I'm missing. Regardless I'll close this as I don't think it's this plugin that is causing problems. Thanks again!
