### ISSUE TITLE
Document how to setup extended clientCapabilities

### ISSUE THREAD

**Issue by mikehaertl** [antosha417/nvim-lsp-file-operations#30]
I'm not sure if I missed anything, but for me the default setup is not enough, because nvim will not include the corresponding capabilities in the LSP `initialize` request.

So for `nvim-lspconfig` I had to add something like this to my config:

```lua
local lspconfig = require'lspconfig'
local util = lspconfig.util

-- Set global defaults for all servers
util.default_config = vim.tbl_extend(
  'force',
  util.default_config,
  {
    capabilities = vim.tbl_deep_extend(
      "force",
      vim.lsp.protocol.make_client_capabilities(),

      -- support added by lsp-file-operations
      {
        workspace = {
          fileOperations = {
            willRename = true,
            didRename = true,
            willCreate = true,
            didCreate = true,
            willDelete = true,
            didDelete = true,
          }
        }
      }
    )
  }
)
```

Shouldn't this be mentioned in the README?

**Comment by antosha417** [comment]
It depends on language server that you are using. Most of language servers do not support all kinds of file operations. 
What exactly does not work for you? What language server are you using?

**Comment by mikehaertl** [comment]
It's [eclipse.jdt.ls](https://github.com/eclipse-jdtls/eclipse.jdt.ls) via [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls).

To clarify: It *does* work - but only if I let neovim report the above client capabilities. Correct me if I'm wrong, but what I think how it works:

 * Client reports its capabilites to server (e.g. `workspace.fileOperations.willRename`)
 * Server responds with an intersection of *all* its supported capabilites and the client capabilities

Without my above change the server response did not include `workspace.fileOperations.willRename` even though the server *does* support this operation.

**Comment by mikehaertl** [comment]
To clarify: `lspconfig.util.default_config.capabilities` configures the *client* capabilities, not the server capabilities.

**Comment by antosha417** [comment]
I get it now. We add recipes for specific language servers to the wiki
https://github.com/antosha417/nvim-lsp-file-operations/wiki

You can also open a pr and add it to readme if you want.

**Comment by mikehaertl** [comment]
So you did not have this problem? Then maybe LSP servers behave differently and only jdt.ls has this problem.

If you think it makes sense I can still provide a PR for the README later.

**Comment by antosha417** [comment]
I mostly use metals language server for scala with https://github.com/scalameta/nvim-metals
I make client capabilities like this and they don't contain any of the file operations
```lua
    local capabilities = vim.lsp.protocol.make_client_capabilities()
```
But still metals language server returns everything. 

I think it is ok to add some specific instructions to the readme, it might save people time.

**Comment by mikehaertl** [comment]
What do you think about providing a utility method that returns the capabilities to add? That's how [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp?tab=readme-ov-file#capabilities) does it. 

It can be used to extend nvim's default capabilities as suggested [here](https://github.com/hrsh7th/cmp-nvim-lsp/issues/38#issuecomment-1815265121). It would look like this:

```lua
local lspconfig = require'lspconfig'
local cmp_nvim_lsp = require'cmp_nvim_lsp'
local lsp_file_operations = require'lsp-file-operations'
local util = lspconfig.util

-- Set global defaults for all servers
util.default_config = vim.tbl_extend(
  'force',
  util.default_config,
  {
    capabilities = vim.tbl_deep_extend(
      "force",
      vim.lsp.protocol.make_client_capabilities(),
      cmp_nvim_lsp.default_capabilities(),
      lsp_file_operations.default_capabilities(),
    )
  }
)
```
