### ISSUE TITLE
Integration with Oil.nvim

### ISSUE THREAD

**Issue by Kyren223** [antosha417/nvim-lsp-file-operations#36]
I personally don't use neotree/nvim-tree but rather Oil.nvim
I would love to see support for that plugin because that's the main plugin I use for file operations like renaming/moving/deleting

**Comment by antosha417** [comment]
Thanks for your suggestion! While I personally don't use Oil.nvim and won't be able to add support for it myself, I'd be more than happy to merge a PR if you or anyone else is willing to contribute this integration.  Feel free to reach out if you have any questions along the way—I’d be happy to help!

**Comment by Kyren223** [comment]
What data is needed for such integration?
Oil.nvim is just a buffer that is being edited, and then when saving it (with :w) it does the changes, so there might be a way to hook into that.
I don't mind helping but I am new to the neovim ecosystem so it'd be hard for me to implement it myself

Also I'd highly recommend checking out oil and trying it yourself for a few days, it's really nice, I used to use neotree but then after using oil for a bit I find myself not even using neotree anymore.
And hey, you might like it and end up implementing it yourself :)

**Comment by chenxin-yan** [comment]
Oil.nvim supports file rename through lsp. I don't think you need this plugin to auto update the file path.

**Comment by Kyren223** [comment]
Oh alright, I wasn't aware, then this issue can be closed
