### ISSUE TITLE
Error for WillRenameNode event

### ISSUE THREAD

**Issue by AminBhst** [antosha417/nvim-lsp-file-operations#7]
Hey!
When renaming a dart file, I get the error below: 
```
Handler for event WillRenameNode errored. nvim-lsp-file-operations/lua/lsp-file-operations/utils.lua:27: attempt to call method 'new' (a nil value)
```
My dart lsp is setup and it does support willRenameFiles request.

**Comment by antosha417** [comment]
Hey! Thank you for reporting! 

Unfortunately I don't have any experience with dart. So it'll take some time for me to debug this. 
But first can you please confirm that you do have https://github.com/nvim-lua/plenary.nvim installed?

**Comment by AminBhst** [comment]
It's okay I would appreciate that.
Yes I do have plenary installed.

**Comment by antosha417** [comment]
@AminBhst, can you please set up this plugin with debug mode enabled and share the log file here?
```lua
require("lsp-file-operations").setup {
  -- used to see debug logs in file `vim.fn.stdpath("cache") .. 'lsp-file-operations.log'`
  debug = true
}
```
I think it might help to dig into the problem

**Comment by AminBhst** [comment]
```
[DEBUG Fri 10 Feb 2023 02:38:47 PM +0330] ...art/nvim-lsp-file-operations/lua/lsp-file-operations.lua:17: Setting up nvim-tree integration
```
Unfortunately this was the only thing that was logged.
@antosha417

**Comment by igorlfs** [comment]
I'm having the same issue with rust-analyzer

**Comment by antosha417** [comment]
@igorlfs,  I'll try to create minimal config for this plugin and rust-analyzer and reproduce

**Comment by AminBhst** [comment]
Can confirm!
Using lowercase path fixes this issue on dartls as well. Now imports are auto-fixed on file rename perfectly.

**Comment by susliko** [comment]
@AminBhst @igorlfs 
Hi! Could you please specify an operating system of use when encountering the problem?

**Comment by AminBhst** [comment]
@susliko I use Fedora Linux

**Comment by igorlfs** [comment]
> @AminBhst @igorlfs Hi! Could you please specify an operating system of use when encountering the problem?

I'm on arch linux
