### ISSUE TITLE
Probably plugin doesn't work with .ts and .tsx files

### ISSUE THREAD

**Issue by lucasrabiec** [antosha417/nvim-lsp-file-operations#9]
Hi, I am using LunarVim, I have installed typescript-language-server. Also typescript and tsx from treesitter. I installed and setup lsp-file-operations. When I rename the filename (.ts or .tsx) through nvim-tree only the filename is changed. No imports are updated. Do you have any ideas about what is wrong?

**Comment by antosha417** [comment]
Hey! You can enable debug mode and see if anything is going on in the logs.

Also which version of typescript language server are you using?

**Comment by lucasrabiec** [comment]
TLS version is 3.3.0

Steps:
1. I opened `lvim`
2. Next I opened nvim-tree `<leader>e` and do rename `r` then confirm
3. Filename changed, imports not
4. Logs from `nvim-lsp-file-operations.log`:
```
[DEBUG Tue Feb 28 22:03:21 2023] ...art/nvim-lsp-file-operations/lua/lsp-file-operations.lua:17: Setting up nvim-tree integration
```

**Comment by KostkaBrukowa** [comment]
As we can see here: https://github.com/typescript-language-server/typescript-language-server#supported-protocol-features `typescript-language-server` does not support [workspace/WillRename](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) operation. Am I right?

**Comment by KostkaBrukowa** [comment]
In order for this plugin to work with `typescript-language-server` it would need to send different command: https://github.com/typescript-language-server/typescript-language-server#rename-file: `workspace/executeCommand` with correct arguments

**Comment by antosha417** [comment]
@KostkaBrukowa, I added support for willRename in this pr: https://github.com/typescript-language-server/typescript-language-server/pull/685
Probably forgot to update readme there. 
During development tested it in neovim with this plugin and everything worked. 

https://github.com/typescript-language-server/typescript-language-server#rename-file: `workspace/executeCommand` will not work. I explained why here https://github.com/antosha417/nvim-lsp-file-operations/issues/6#issuecomment-1407791802

I don't have a lot of free time right now, sorry. Will take a look at this issue as soon as I can.

**Comment by KostkaBrukowa** [comment]
Oh you are right - I've had old version of TLS. After updating it works for me. Thanks!

**Comment by lucasrabiec** [comment]
I changed my configuration to LazyVim so we can close it. One more thing, is it possible to make it work with neo-tree?

**Comment by antosha417** [comment]
Hey @lucasrabiec. I will close this issue for now. 
From what I can see neo-tree also has events api. So it can be possible to support it. 
However right now I have very little free time and motivation to do it. But you can always open a pr with neo-tree support. I'm here to answer any questions you might have about implementation.
